Repository gilsangwoo/ssulsday, pull requests merged in 2019-11, with the labels that each got.

#6 #3 input컴포넌트 및 button컴포넌트 수정
  src/App.js
  src/index.js
  src/views/components/Ellipse/Ellipse.js
  src/views/components/Ellipse/Ellipse.scss
  src/views/components/Ellipse/index.js
  src/views/components/Hash/Hash.js
  src/views/components/Hash/Hash.scss
  src/views/components/Hash/index.js
  src/views/components/Icon/Icon.js
  src/views/components/InputBox/InputBox.js
  src/views/components/InputBox/InputBox.scss
  src/views/components/InputBox/index.js
  src/views/components/PlaceCard/PlaceCard.js
  src/views/components/PlaceCard/PlaceCard.scss
  src/views/components/PlaceCard/index.js
  src/views/components/PlaceCard/place.png
  src/views/components/TapButton/TapButton.js
  src/views/components/TapButton/TapButton.scss
  src/views/components/TapButton/index.js
  src/views/style/base.scss
  src/views/style/font.scss
  src/views/style/index.scss
  src/views/style/variable.scss
Labels: documentation

#8 #7 라우터 제작
  package.json
  src/App.js
  src/Root.js
  src/index.js
  src/views/App.js
  src/views/App.scss
  src/views/pages/NotFoundPage.js
  src/views/pages/SamplePage.js
  src/views/pages/index.js
  src/views/style/font.scss
Labels: help wanted

#19 [#16]/feat api 추가
  .gitignore
  package.json
  src/context/serverContext.js
  src/domain/Card.js
  src/domain/Comment.js
  src/domain/Post.js
  src/domain/User.js
  src/repository/ActivityRepository.js
  src/repository/CardRepository.js
  src/repository/CommentRepository.js
  src/repository/ContactRepository.js
  src/repository/LikeRepository.js
  src/repository/PostRepository.js
  src/repository/UserRepository.js
Labels: feature

#26 [#9] 회원가입과 비밀번호찾기 페이지 제작
  src/views/App.js
  src/views/components/Authenticationbutton/Authenticationbutton.js
  src/views/components/Authenticationbutton/Authenticationbutton.scss
  src/views/components/FindPassword/FindPasswordTemplate/FindPasswordTemplate.js
  src/views/components/FindPassword/FindPasswordTemplate/FindPasswordTemplate.scss
  src/views/components/FindPassword/FindPasswordTemplate/index.js
  src/views/components/InputBox/InputBox.js
  src/views/components/InputBox/InputBox.scss
  src/views/components/signUp/SignUpAuth/SignUpAuth.js
  src/views/components/signUp/SignUpAuth/SignUpAuth.scss
  src/views/components/signUp/SignUpAuth/index.js
  src/views/components/signUp/SignUpForm/SignUpForm.js
  src/views/components/signUp/SignUpForm/SignUpForm.scss
  src/views/components/signUp/SignUpForm/index.js
  src/views/components/signUp/SignUpHeader/SignUpHeader.js
  src/views/components/signUp/SignUpHeader/SignUpHeader.scss
  src/views/components/signUp/SignUpHeader/index.js
  src/views/components/signUp/SignUpPrivate/SignUpPrivate.js
  src/views/components/signUp/SignUpPrivate/index.js
  src/views/components/signUp/SignUpTemplate/SignUpTemplate.js
  src/views/components/signUp/SignUpTemplate/index.js
  src/views/pages/FindPasswordPage.js
  src/views/pages/SignUpPage.js
  src/views/pages/index.js
Labels: feature

#28 [#22] 마이페이지 아이콘 수정
  src/Root.js
  src/domain/User.js
  src/index.js
  src/repository/CardRepository.js
  src/repository/UserRepository.js
  src/views/components/Authenticationbutton/Authenticationbutton.scss
  src/views/components/Card/CardView.js
  src/views/components/Card/CardView.scss
  src/views/components/CommentCreate/CommentCreate.scss
  src/views/components/CommentCreate/commentCreate.js
  src/views/pages/Listpage/Listpage.js
  src/views/pages/LoginPage/LoginPage.js
  src/views/pages/Mypage/Help/Help.js
  src/views/pages/Mypage/Help/Help.scss
  src/views/pages/Mypage/Help/index.js
  src/views/pages/Mypage/Mypage.js
  src/views/pages/Mypage/Mypage.scss
  src/views/pages/Mypage/Notice/Notice.js
  src/views/pages/Mypage/Notice/Notice.scss
  src/views/pages/Mypage/Notice/index.js
  src/views/pages/Mypage/index.js
  src/views/pages/Mypage/item/index.js
  src/views/pages/Mypage/item/item.js
  src/views/pages/Mypage/item/item.scss
  src/views/pages/Mypage/question/index.js
  src/views/pages/Mypage/question/question.js
  src/views/pages/Mypage/question/question.scss
  src/views/pages/SamplePage.js
  src/views/pages/UpdateUserpage/UpdateUser.js
  src/views/pages/UpdateUserpage/UpdateUser.scss
  src/views/pages/UpdateUserpage/index.js
Labels: feature
